### ISSUE TITLE
[Meta] drop deprecated AppSearch Java library

### ISSUE THREAD

**Issue by andsel** [logstash-plugins/logstash-output-elastic_app_search#12]
The client library used by this plugin (https://github.com/swiftype/swiftype-app-search-java) has been deprecated, so this plugin has to be updated or to use the Ruby client (which is maintained) or to use the plain Rest API. In the same time introduce integration tests.
- [x] change `.ci` to spawn an app search instance to be used into integration tests PR #13 
- [x] write integration tests against the local app search instance #14 
- [x] drop the deprecated library and rewrite the code to interact with app search #15

**Comment by andsel** [comment]
Closed with release  `1.1.0`

**Comment by acchen97** [comment]
@andsel good work. Do we plan to bundle this new version by default with LS 7.9?

**Comment by andsel** [comment]
Thanks Alvin, yes the target is that
